config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'

  get '/portfolio' => 'pages#portfolio'
  get '/about' => 'pages#about'
  get '/experience' => 'pages#experience'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showcase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=PT+Serif&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="about-container">
  <div class=left-banner></div>
  <%= render :partial => 'shared/left_banner' %>
  <div class="middle-text">
    <div class="about-text">
      <p class="portfolio-header">ABOUT</p>
      <hr class='break'>
      <p class='text-spacing'> After graduating from Le Wagon's <a class='about-link' href='https://www.lewagon.com/'>coding bootcamp</a>, I spent several months
        building applications in an effort to shore up my ability.
      <p class='text-spacing'> Shortly after deploying this site, I received an offer
        to work for <a href="https://www.approveshield.com/"class="about-link">ApproveShield</a> as a <span class="blue">
          full stack web developer</span>. Being a start-up company with just 1 other developer,
        I had to wear many hats, with responsibilities ranging from front/backend work,
        to maintaining the application's server, to hiring new engineers.
      </p>
        <p class='text-spacing'>
        However, the bulk of my work was centered on <span class="bold">improving the application
        to increase the speed at which employees could do their job.</span> This included:
      </p>
      <ul class="list">
        <li>Improving UI to minimize scrolling</li>
        <li>Writing faster SQL queries</li>
        <li>Lazy loading data to decrease page load time</li>
        <li>Using WickedPDF gem to generate documents from forms</li>
        <li>Integrating APIs</li>
      </ul>
      <p class='text-spacing'>
           These crucial contributions helped the company
           increase revenue by <span class="blue">300%</span>.
      </p>
      <hr>
      <p class='text-spacing'>
        Seeking a better opportunity, I began working at <a href="https://www.assurant.com/"class="about-link">Assurant</a> to help develop
        <span class="blue"> Pocketgeek Home</span>, an application which can be found on <a href="https://apps.apple.com/us/app/pocket-geek-home/id1410854379" class="about-link">iOS</a>,
        <a href="https://play.google.com/store/apps/details?id=com.pocketgeek.home.android&hl=en_US&gl=US&pli=1" class="about-link">Android </a>, and <a href="https://www.pocketgeekhome.com/" class="about-link">Web</a>.
        A large portion of my time here was spent <span class="bold">engineering a white-labeled version
        of the app in conjunction with T-Mobile</span>, which allows users to add insurance
        to pre-owned phones without getting it physically inspected. Some of my contributions
        included:
      </p>
        <ul class="list">
          <li>Developing a backend API with TypeScript/GraphQL to communicate with database</li>
          <li>Integrating hardware test SDK for device diagnostics</li>
          <li>Coordinating with UI team to develop user flow for device registration</li>
          <li>Creating responsive screens to work on mobile and web</li>
        </ul>
        <p class='text-spacing'>
        This allowed me to expand my toolset,
        having the chance to work with a variety of newer technologies, such as <span class="blue">GraphQL</span>,
        <span class="blue">React Native</span>, <span class="blue">Redux</span>, <span class="blue">TypeScript</span>, and <span class="blue">Docker</span>, while also continuing to strengthen
        my ability in <span class="blue">Ruby on Rails</span>, <span class="blue">MySQL2</span>, and <span class="blue">Javascript</span>. 
      </p>
    </div>
  </div>
  <div class="right-banner"></div>
</div>

app/views/pages/experience.html.erb
<div class="home-container">

  <%= render :partial => 'shared/left_banner' %>
   <div class="portfolio-text">
    <p class="portfolio-header"> EXPERIENCE</p>
    <p class="portfolio-paragraph"> Details of my professional working experience as a software engineer</p>
    <hr class="dashed">
     <div class='experience-project'>
       <div class="experience-text">
         <div class="experience-titles">
           <div class="experience-company">
             <div class="company-logo">
               <%= image_tag 'loadup-icon.webp' %>
             </div>
             <div class="experience-header">
               LoadUp
             </div>
           </div>
           <p class='work-title'>Software Engineer II · Remote</p>
           <p class='work-title'style='color: #555555;'>Jan 2023 - Jan 2024  1 yr 1 mos</p>
         </div>

         <p class="project-bold">Worked on employee facing web app to facilitate management of customer orders, as well as customer facing iOS/Android apps to assist 3rd-party drivers. Some of my responsibilities included:
         </p>
         <ul>



           <li>Building out web and mobile apps using Rails, Turbo Native, Stimulus,
             GraphQL, and React Native</li>
           <li>Eliminating time-consuming processes to drastically improve worker
             productivity</li>
           <li>Performing daily code reviews and working closely with teammates to
             deliver new features</li>
         </ul>
         <button class="view-online">
           <i class="fa fa-external-link white-color"></i>
           <a href="https://goloadup.com/" style='text-decoration: none; color:white'>
             View online
           </a>
         </button>
         <button class="view-online">
           <i class="fa fa-apple white-color"></i>
           <a href="https://apps.apple.com/us/app/loadup-loader/id6448062554" style='text-decoration: none; color:white'>
             iOS
           </a>
         </button>
         <button class="view-online">
           <i class="fa fa-android white-color"></i>
           <a href="https://play.google.com/store/apps/details?id=com.loadup.loader.android&hl=en_US&gl=US" style='text-decoration: none; color:white'>
             Android
           </a>
         </button>
         <p class="tech">TECHNOLOGIES</p>
         <button class="tech-button">RUBY ON RAILS</button>
         <button class="tech-button">JAVASCRIPT</button>
         <button class="tech-button">STIMULUS</button>
         <button class="tech-button">REACT NATIVE</button>
         <button class="tech-button">HEROKU</button>




       </div>
       <div class="experience-image">
         <%= image_tag 'loadup.png' %>
       </div>
     </div>
     <hr class="dashed">
    <div class='experience-project'>
      <div class="experience-text">
        <div class="experience-titles">
          <div class="experience-company">
            <div class="company-logo">
              <%= image_tag 'Assurant_logo.png' %>
            </div>
            <div class="experience-header">
              Assurant Inc.
            </div>
          </div>
          <p class='work-title'>Staff Software Engineer · Remote</p>
          <p class='work-title'style='color: #555555;'>Sept 2021 - Oct 2022  1 yr 2 mos</p>
        </div>

        <p class="project-bold">Worked primarily on Assurant's PocketGeek Home application, which provides support and allows users to
          file insurance claims for various technological devices. Some of my responsibilities included:
        </p>
        <ul>



          <li>Developing and maintaining API backends written with Rails, Javascript, and TypeScript</li>
          <li>Building front-end interfaces for iOS, Android, and Web using React Native</li>
          <li>Coordinating with T-Mobile to develop application for adding insurance to mobile phones</li>
        </ul>
        <button class="view-online">
          <i class="fa fa-external-link white-color"></i>
          <a href="https://www.pocketgeekhome.com/" style='text-decoration: none; color:white'>
            View online
          </a>
        </button>
        <button class="view-online">
          <i class="fa fa-apple white-color"></i>
          <a href="https://apps.apple.com/us/app/pocket-geek-home/id1410854379" style='text-decoration: none; color:white'>
            iOS
          </a>
        </button>
        <button class="view-online">
          <i class="fa fa-android white-color"></i>
          <a href="https://play.google.com/store/apps/details?id=com.pocketgeek.home.android&hl=en_US&gl=US&pli=1" style='text-decoration: none; color:white'>
            Android
          </a>
        </button>
        <p class="tech">TECHNOLOGIES</p>
        <button class="tech-button">RUBY ON RAILS</button>
        <button class="tech-button">JAVASCRIPT</button>
        <button class="tech-button">TYPESCRIPT</button>
        <button class="tech-button">REACT NATIVE</button>
        <button class="tech-button">AWS</button>




      </div>
      <div class="experience-image">
        <%= image_tag 'PG_Home.png' %>
      </div>
    </div>
    <hr class="dashed">
    <div class='experience-project'>
      <div class="experience-text">
        <div class="experience-titles">
          <div class="experience-company">
            <div class="company-logo">
              <%= image_tag 'ApproveShield.png' %>
            </div>
            <div class="experience-header">
              ApproveShield LLC.
            </div>
          </div>
          <p class='work-title'>Full Stack Developer · Richardson, TX</p>
          <p class='work-title'style='color: #555555;'>Nov 2020 - Sept 2021  11 mos</p>
        </div>
        <p class="project-bold">Helped build and maintain a web application used internally, by rental communities, and lease applicants
          to process rental applications during a period which saw 300% growth. Some of my responsibilities included:
        </p>
        <ul>
          <li>Developing new features and integrating APIs to improve app functionality</li>
          <li>Refactoring existing code base to be more efficient</li>
          <li>Monitoring Heroku logs and server health</li>
          <li>Writing test suite to successfully migrate to newer version of Rails</li>
          <li>Helping to interview and hire other developers</li>
        </ul>
        <button class="view-online">
          <i class="fa fa-external-link white-color"></i>
          <a href="https://www.approveshield.com/" style='text-decoration: none; color:white'>
            View online
          </a>
        </button>
        <p class="tech">TECHNOLOGIES</p>
        <button class="tech-button">RUBY ON RAILS</button>
        <button class="tech-button">JAVASCRIPT</button>
        <button class="tech-button">JQUERY</button>
        <button class="tech-button">HEROKU</button>
        <button class="tech-button">MYSQL2</button>
      </div>
      <div class="experience-image">
        <%= image_tag 'ApproveShield_Big.png' %>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="background-image">
  <div class='home-container'>
  <%= render :partial => 'shared/left_banner' %>
    <div class="home-text">
      <h1> Hi, I'm Max,</h1>
      <h2> a software engineer specialized in both</h2>
      <h2 style="font-weight: bold"> front-end and back-end.</h2>
      <div class="home-buttons">
        <div>
          <%= link_to 'PORTFOLIO', portfolio_path, method: :get, class: 'home-button' %>
        </div>
        <br>
        <br>
        <div>
        <%= link_to 'EXPERIENCE', experience_path,  method: :get, class: 'home-button' %>
        </div>
        <br>
        <br>
        <div>
        <%= link_to 'ABOUT', about_path,  method: :get, class: 'home-button' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/portfolio.html.erb
<div class="home-container">

  <%= render :partial => 'shared/left_banner' %>
   <div class="portfolio-text">
    <p class="portfolio-header"> PORTFOLIO</p>
    <p class="portfolio-paragraph"> The following are a list of my works. Designed entirely be me unless specified</p>
     <hr class="dashed">
     <div class='project'>
       <div class="project-text">
         <p class='project-header'>ZeroSixty</p>
         <p class='project-subtitle'>A next-gen web app featuring 0-60 times for over 10,000 cars</p>
         <p class="project-bold"> ZeroSixty aims to be the go-to source for car 0-60 times with a modern interface and cutting edge features. It:</p>
         <ul>
           <li>Allows users to view 0-60 times, quarter mile times, and specs for thousands of cars</li>
           <li>Provides easy navigation and filtering with a mobile first design</li>
           <li>Integrates with OpenAI to provide general car info, pricing, interesting facts, and more</li>
         </ul>
         <button class="view-online">
           <i class="fa fa-external-link white-color"></i>
           <a href="https://www.zerosixtytimes.com/" style='text-decoration: none; color:white'>
             View online
           </a>
         </button>
         <p class="tech">TECHNOLOGIES</p>
         <button class="tech-button">RUBY ON RAILS</button>
         <button class="tech-button">JAVASCRIPT</button>
         <button class="tech-button">TAILWIND</button>
         <button class="tech-button">STIMULUS</button>



       </div>
       <div class="project-image">
         <%= image_tag 'zerosixtyshowcase.png' %>
       </div>
     </div>
    <hr class="dashed">
    <div class='project'>
      <div class="project-text">
        <p class='project-header'>The Simple Diary</p>
        <p class='project-subtitle'>A Diary designed to be intuitive and easy to use</p>
        <p class="project-bold"> The Simple Diary allows users to record their entries
        without having to navigate all the unnecessary bloat that plagues similar applications.
       The app does several things:</p>
        <ul>
          <li>Allows users to create and update entries, with timestamps</li>
          <li>Provides simple navigation of entries using a single-page carousel</li>
          <li>Works on desktops/tablets (<strong>NOT</strong> designed for mobile)</li>
        </ul>
        <button class="view-online">
          <i class="fa fa-external-link white-color"></i>
          <a href="https://www.thesimplediary.com/" style='text-decoration: none; color:white'>
            View online
          </a>
        </button>
        <p class="tech">TECHNOLOGIES</p>
        <button class="tech-button">RUBY ON RAILS</button>
        <button class="tech-button">JAVASCRIPT</button>
        <button class="tech-button">JQUERY</button>
        <button class="tech-button">BOOTSTRAP</button>



      </div>
      <div class="project-image">
        <%= image_tag 'TheSimpleDiary.png' %>
      </div>
    </div>
    <hr class="dashed">
      <div class='project'>
        <div class="project-text">
          <p class='project-header'>T-Mobile Plan Comparison Tool</p>
          <p class='project-subtitle'>An interactive plan comparison tool designed for front-line use</p>
          <p class="project-bold"> This plan comparison tool allows front line T-Mobile employees
          to quickly compare most used T-Mobile plans by doing the following: </p>

          <ul>
            <li> Listing all features of common T-Mobile plans in convenient layout</li>
            <li> Allowing users to calculate cost of up to 12 lines of service on each plan</li>
            <li> Changing layout dynamically based off of device (responsive)
          </ul>
          <p style='font-style: italic'> The app is actively being used in several retail locations.</p>
        <button class="view-online">
          <i class="fa fa-external-link white-color"></i>
          <a href="http://tmobile-plans.herokuapp.com/" style='text-decoration: none; color:white'>
            View online
          </a>
        </button>
        <p class="tech">TECHNOLOGIES</p>
        <button class="tech-button">RUBY ON RAILS</button>
        <button class="tech-button">JAVASCRIPT</button>
      </div>
      <div class="project-tmo">
        <%= image_tag 'Tmobile.png' %>
      </div>
    </div>
    <hr class="dashed">
      <div class='project'>
        <div class="project-text">
          <p class='project-header'>The Goody Goody</p>
          <p class='project-subtitle'>Vinyl at the cheapest price</p>
          <p class="project-bold"> Compare the prices of Vinyl record's from Berlin's
          most prominent record stores. The app aim's to do the following</p>
          <ul>
            <li> Collect information from all records stores in Berlin (starting) and compare prices</li>
            <li> Allow the user to preview the tracks via Spotify API</li>
            <li> Save releases to wishlist and be notified when it is back in stock</li>
            <li> Connect with record stores so user can place orders</li>
          </ul>
          <p style='font-style: italic'> The app is still being developed by me and one other person and is currently in Alpha phase.</p>
        <button class="view-online">
          <i class="fa fa-external-link white-color"></i>
          <a href="https://www.thegoodygoody.com/" style='text-decoration: none; color:white'>
            View online
          </a>
        </button>
        <p class="tech">TECHNOLOGIES</p>
        <button class="tech-button">RUBY ON RAILS</button>
        <button class="tech-button">BOOTSTRAP</button>
        <button class="tech-button">JAVASCRIPT</button>
      </div>
      <div class="project-tgg">
        <%= image_tag 'thegoodygoody.png' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_left_banner.html.erb
<div class="home-banner">
  <div class="banner-top">
    <div class="desktop">
      <div id="avatar">
        <!-- <image src="images/avatar.jpg"> -->
      </div>
      <div class="avatar-text name"> MAX RAMIREZ-DE-ARELLANO</div>
      <div class="avatar-text role"> FULL STACK ENGINEER</div>

      <div class="home-list">
        <ul style="list-style-type:none;">
          <div class="home-list-item">
            <li><%= link_to'HOME', root_path, class: 'link'%></li>
            <li class="arrow">></li>
          </div>
          <div class="home-list-item">
            <li><%= link_to'PORTFOLIO', portfolio_path, class: 'link'%></li>
            <li class="arrow">></li>
          </div>
          <div class="home-list-item">
            <li><%= link_to'EXPERIENCE', experience_path, class: 'link'%></li>
            <li class="arrow">></li>
          </div>
          <div class="home-list-item">
            <li><%= link_to'ABOUT', about_path, class: 'link'%></li>
            <li class="arrow">></li>
          </div>
        </ul>
      </div>
    </div>

    <div class="home-list bottom">
      <ul style="list-style-type:none;">
        <li  class="in-touch" style="font-size: .6rem">GET IN TOUCH</li>
      </ul>
      <div class="icons">
        <a href="https://github.com/maxfrda" class="fa fa-github fa-2x icon" aria-hidden="true"></a>
        <a href="mailto: maxfrda@gmail.com" class="fa fa-envelope fa-2x icon" aria-hidden="true"></a>
        <a href="https://www.linkedin.com/in/max-arellano-6a416b259/" class="fa fa-linkedin fa-2x icon" aria-hidden="true"></a>
        <a class="fa fa-bars fa-2x icon hamburger"></a>
      </div>

      <div class="dropdown">
        <hr>
        <div class='dropdown-items'>
          <div><%= link_to'HOME', root_path, method: :get, class: 'dropdown-item'%></div>
          <div><%= link_to'PORTFOLIO', portfolio_path, method: :get, class: 'dropdown-item'%></div>
          <div><%= link_to'EXPERIENCE', experience_path, method: :get, class: 'dropdown-item'%></div>
          <div><%= link_to'ABOUT', about_path, method: :get, class: 'dropdown-item'%></div>
        </div>
      </div>

    </div>
  </div>
</div>